language: java
sudo: false
jdk: openjdk8

os:
  - linux
  - windows

before_install:
  - "echo $JAVA_OPTS"

script:
  - mvn install -B -V
  - mvn javadoc:jar
  - mvn javadoc:test-aggregate

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash <(curl -s https://codecov.io/bash); fi
